export default [
  {
    shortName: 'fm4',
    name: 'Mosaique FM',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosalive',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: true,
  },
  {
    shortName: 'msq1',
    name: 'Mosaique FM Tounsi',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosatounsi',
    website: 'http://mosaiquefm.net/',
    color: '#BF0C12',
    dark: false,
  },
  {
    shortName: 'msq2',
    name: 'Mosaique FM Tarab',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosatarab',
    website: 'http://mosaiquefm.net/',
    color: '#198CFC',
    dark: false,
  },
  {
    shortName: 'msq3',
    name: 'Mosaique FM Gold',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosagold',
    website: 'http://mosaiquefm.net/',
    color: '#C7AD4F',
    dark: false,
  },
  {
    shortName: 'msq4',
    name: 'Mosaique FM DJ',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosadj',
    website: 'http://mosaiquefm.net/',
    color: '#BD25F8',
    dark: false,
  },
  {
    shortName: 'chm',
    name: 'Chemes FM',
    streamurl: 'http://stream6.tanitweb.com/shems',
    website: 'https://www.shemsfm.net/',
    color: '#EEBF15',
    dark: false,
  },
  {
    shortName: 'jaw',
    name: 'Jawhra',
    streamurl: 'http://streaming2.toutech.net:8000/jawharafm',
    website: 'https://www.jawharafm.net/',
    color: '#2472B0',
    dark: false,
  },
  {
    shortName: 'ifm',
    name: 'ifm',
    streamurl: 'http://ifm.tn:8000/direct',
    website: 'http://ifm.tn',
    color: '#037BA3',
    dark: false,
  },
  {
    shortName: 'zay',
    name: 'Zaytouna FM',
    streamurl: 'http://stream8.tanitweb.com/zitounafm',
    color: '#7AAE2D',
    dark: false,
  },
  {
    shortName: 'djr',
    name: 'Djerid',
    streamurl: 'http://164.132.44.122:9998/;listen.mp3',
    website: 'http://www.djeridfm.com/',
    color: '#C0610D',
    dark: false,
  },
  {
    shortName: 'bab',
    name: 'Babnet',
    streamurl: 'http://193.95.93.29:8080/;stream.mp3',
    website: 'https://www.babnet.net',
    color: '#EF512C',
    dark: false,
  },
  {
    shortName: 'sij',
    name: 'Sijal FM',
    streamurl: 'http://listen.radionomy.com/sijal-fm',
    color: '#D48213',
    dark: false,
  },
  {
    shortName: 'wat1',
    name: 'Watania 1',
    streamurl: 'http://rtstream.tanitweb.com/nationale',
    website: 'http://www.radionationale.tn/',
    color: '#DF231B',
    dark: false,
  },
  {
    shortName: 'rsfax',
    name: 'Radio Sfax',
    streamurl: 'http://rtstream.tanitweb.com/sfax',
    website: 'http://www.radionationale.tn/',
    color: '#8AC937',
    dark: false,
  },
  {
    shortName: 'rjeu',
    name: 'Radio Jeunes Tunisie',
    streamurl: 'http://rtstream.tanitweb.com/jeunes',
    website: 'http://www.radionationale.tn/',
    color: '#FFE21A',
    dark: false,
  },
  {
    shortName: 'rmon',
    name: 'Radio Monastir',
    streamurl: 'http://rtstream.tanitweb.com/monastir',
    website: 'http://www.radionationale.tn/',
    color: '#38BAF8',
    dark: false,
  },
  {
    shortName: 'rtci',
    name: 'RTCI',
    streamurl: 'http://rtstream.tanitweb.com/rtci',
    website: 'http://www.radionationale.tn/',
    color: '#ED5282',
    dark: false,
  },
  {
    shortName: 'rkef',
    name: 'Radio Kef',
    streamurl: 'http://rtstream.tanitweb.com/kef',
    website: 'http://www.radionationale.tn/',
    color: '#D41E73',
    dark: false,
  },
  {
    shortName: 'rghaf',
    name: 'Radio Gafsa',
    streamurl: 'http://rtstream.tanitweb.com/gafsa',
    website: 'http://www.radionationale.tn/',
    color: '#FF7000',
    dark: false,
  },
  {
    shortName: 'rcul',
    name: 'Radio Culture',
    streamurl: 'http://rtstream.tanitweb.com/culturelle',
    website: 'http://www.radionationale.tn/',
    color: '#101981',
    dark: false,
  },
  {
    shortName: 'rtat',
    name: 'Radio Tataouine',
    streamurl: 'http://rtstream.tanitweb.com/tataouine',
    website: 'http://www.radionationale.tn/',
    color: '#FFA601',
    dark: false,
  },
  {
    shortName: 'expr',
    name: 'Express FM',
    streamurl: 'http://expressfm.ice.infomaniak.ch/expressfm-64.mp3',
    website: 'www.radioexpressfm.com',
    color: '#037BA3',
    dark: false,
  },
  {
    shortName: 'knoo',
    name: 'Kn00z FM',
    streamurl: 'http://streaming.knoozfm.net:8000/knoozfm',
    website: 'www.knoozfm.net',
    color: '#FFE32A',
    dark: false,
  },
  {
    shortName: 'sabr',
    name: 'Sabra FM',
    streamurl: 'http://stream6.tanitweb.com/sabrafm',
    website: 'https://www.radiosabrafm.net/',
    color: '#24882D',
    dark: false,
  },
  {
    shortName: 'diw',
    name: 'Diwan FM',
    streamurl: 'http://stream8.tanitweb.com/diwanfm',
    website: 'http://www.diwanfm.net/',
    color: '#1EB8D3',
    dark: false,
  },
  {
    shortName: 'qur',
    name: 'Radio Quran',
    streamurl: 'http://5.135.194.225:8000/live',
    color: '#DD264B',
    dark: false,
  },
  {
    shortName: 'misk',
    name: 'Radio Misk FM',
    streamurl: 'http://178.32.253.134:8000/stream?type=.mp3',
    website: 'https://misk.tn/',
    color: '#9D9D9D',
    dark: false,
  },
  {
    shortName: 'uly',
    name: 'Ulysse FM',
    streamurl: 'http://188.165.79.152:9990/;stream.mp3',
    website: 'http://www.ulysse-fm.net/',
    color: '#0084B7',
    dark: false,
  },
  {
    shortName: 'rmed',
    name: 'Radio Med Tunisie',
    streamurl: 'http://stream6.tanitweb.com/radiomed',
    website: 'http://radiomedtunisie.com/',
    color: '#128FC3',
    dark: false,
  },
  {
    shortName: 'kar',
    name: 'Karama FM',
    streamurl: 'http://serveur.wanastream.com:64900/;',
    website: 'http://karamafm.com/',
    color: '#8A1F27',
    dark: false,
  },
  {
    shortName: 'oxy',
    name: 'Oxygene FM Bizerte',
    streamurl: 'http://radiooxygenefm.ice.infomaniak.ch/radiooxygenefm-64.mp3',
    website: 'https://www.oxygenefm.com/',
    color: '#0D3F79',
    dark: false,
  },
];
