export default [
  {
    shortName: 'fm4',
    name: 'Mosaique FM',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosalive',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: true,
  },
  {
    shortName: 'msq1',
    name: 'Mosaique FM Tounsi',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosatounsi',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'msq2',
    name: 'Mosaique FM Tarab',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosatarab',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'msq3',
    name: 'Mosaique FM Gold',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosagold',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'msq4',
    name: 'Mosaique FM DJ',
    streamurl: 'http://radio.mosaiquefm.net:8000/mosadj',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'chm',
    name: 'Chamess FM',
    streamurl: 'http://stream6.tanitweb.com/shems',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'jaw',
    name: 'Jawhra',
    streamurl: 'http://streaming2.toutech.net:8000/jawharafm',
    website: 'http://mosaiquefm.net/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'ifm',
    name: 'ifm',
    streamurl: 'http://ifm.tn:8000/direct',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'zay',
    name: 'Zaytouna FM',
    streamurl: 'http://stream8.tanitweb.com/zitounafm',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'djr',
    name: 'Djerid',
    streamurl: 'http://164.132.44.122:9998/;listen.mp3',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'bab',
    name: 'Babnet',
    streamurl: 'http://193.95.93.29:8080/;stream.mp3',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'sij',
    name: 'Sijal FM',
    streamurl: 'http://listen.radionomy.com/sijal-fm',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'wat1',
    name: 'Watania 1',
    streamurl: 'http://rtstream.tanitweb.com/nationale',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rsfax',
    name: 'Radio Sfax',
    streamurl: 'http://rtstream.tanitweb.com/sfax',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rjeu',
    name: 'Radio Jeunes Tunisie',
    streamurl: 'http://rtstream.tanitweb.com/jeunes',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rmon',
    name: 'Radio Monastir',
    streamurl: 'http://rtstream.tanitweb.com/monastir',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rtci',
    name: 'RTCI',
    streamurl: 'http://rtstream.tanitweb.com/rtci',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rkef',
    name: 'Radio Kef',
    streamurl: 'http://rtstream.tanitweb.com/kef',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rghaf',
    name: 'Radio Gafsa',
    streamurl: 'http://rtstream.tanitweb.com/gafsa',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rcul',
    name: 'Radio Culture',
    streamurl: 'http://rtstream.tanitweb.com/culturelle',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rtat',
    name: 'Radio Tataouine',
    streamurl: 'http://rtstream.tanitweb.com/tataouine',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'expr',
    name: 'Express FM',
    streamurl: 'http://expressfm.ice.infomaniak.ch/expressfm-64.mp3',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'knoo',
    name: 'Kn00z FM',
    streamurl: 'http://streaming.knoozfm.net:8000/knoozfm',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'sabr',
    name: 'Sabra FM',
    streamurl: 'http://stream6.tanitweb.com/sabrafm',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'diw',
    name: 'Diwan FM',
    streamurl: 'http://stream8.tanitweb.com/diwanfm',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'qur',
    name: 'Radio Quran',
    streamurl: 'http://5.135.194.225:8000/live',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'misk',
    name: 'Radio Misk FM',
    streamurl: 'http://178.32.253.134:8000/stream?type=.mp3',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'uly',
    name: 'Ulysse FM',
    streamurl: 'http://188.165.79.152:9990/;stream.mp3',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rmed',
    name: 'Radio Med Tunisie',
    streamurl: 'http://stream6.tanitweb.com/radiomed',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'sara',
    name: 'Saraha FM',
    streamurl: 'http://ns326208.ip-37-59-9.eu:8000/sarahafm',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'mfm',
    name: 'MFM Tunisie',
    streamurl: 'http://92.222.225.69:9300/;',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rkel',
    name: 'Radio Kelma FM',
    streamurl: 'http://mdigital.agency:8000/radiokelma',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'rib',
    name: 'Ribat FM',
    streamurl: 'http://streaming.ribatfm.tn:8000/live',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'kar',
    name: 'Karama FM',
    streamurl: 'http://serveur.wanastream.com:64900/;',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'ra6',
    name: 'Radio 6',
    streamurl: 'http://streaming.radio6tunis.net:8000/radio6tunis',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'mouj',
    name: 'Mouja FM',
    streamurl: 'http://87.117.197.33:5258/;',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'oxy',
    name: 'Oxygene FM Bizerte',
    streamurl: 'http://radiooxygenefm.ice.infomaniak.ch/radiooxygenefm-64.mp3',
    website: 'http://ifm.tn',
    color: '#D80926',
    dark: false,
  },
];
